services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount the entire 'key' directory as read-only.
      # This makes the service account key available to the application.
      - ./key:/app/key:ro
      # Mount other necessary directories
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend